-- Audit finding: student_work, publications, and partners had public
-- SELECT (approved/active only — correct, kept as-is) and public
-- INSERT (for submissions — correct, kept as-is), but NO update or
-- delete policy at all. This meant every Approve / Reject / Hide /
-- Delete action in the Community admin page was silently failing,
-- the same root cause class as the earlier invoices bug.
--
-- IMPORTANT: unlike invoices, this fix does NOT grant `using (true)`
-- on SELECT/UPDATE/DELETE to the anon key. The Community admin page
-- is a client component and can only ever use the public anon key —
-- broadening these policies for "true" would mean ANY website visitor
-- could read pending/rejected submissions or modify/delete rows
-- directly via the Supabase JS client in their browser console, since
-- the anon key is necessarily embedded in the public site's bundle.
--
-- Instead: admin moderation (approve/reject/delete/hide) now goes
-- through server-side API routes using the service-role key (see
-- app/api/admin/community/route.ts), which bypasses RLS safely and
-- is never exposed to the browser. RLS here stays tight, matching
-- what a logged-out visitor should actually be allowed to do.
--
-- email_logs / email_templates: same fix, no privacy concern there
-- since neither table is ever read by the public-facing site at all
-- — admin-only data, so service-role access via API routes is the
-- correct and only access path. RLS stays fully locked (no policies
-- needed beyond what's already enforced by going through the API).

-- UPDATE: this same fix was also applied to the `testimonials` table
-- (no migration exists for it in this repo at all — its schema and
-- RLS state predate the migrations folder and could not be verified
-- from code) via app/api/admin/testimonials/route.ts, and to invoices'
-- permanent-delete capability via the DELETE handler added to
-- app/api/invoices/route.ts. Both required a direct route-level admin
-- auth check (see lib/admin/requireAdmin.ts) rather than relying on
-- the proxy, since /api/invoices does not live under /api/admin/ and
-- is therefore not covered by the proxy's matcher.
